#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."
START_TIME=$(date +%s.%N)

echo "🚀 Testing app..."
xcodebuild \
    test \
    -project Browserino.xcodeproj \
    -scheme Browserino \
    -destination "platform=iOS Simulator,arch=arm64,id=F57EC888-735B-4165-8842-985CE251390D" \
    -quiet \
    "$@"

END_TIME=$(date +%s.%N)
ELAPSED_TIME=$(echo "$END_TIME - $START_TIME" | bc --mathlib | xargs printf "%.2f\n")
echo "✅ Running in $ELAPSED_TIME seconds!"

